data = {
    "en": {
        "translation": {
            "WELCOME_MSG": "Welcome to Blindfold Chess! Would you like to play a Match, practice with Puzzles, or train your visualization with Squares?",
            "HELP_MSG": "You can play matches, solve puzzles, or practice square colors. Say 'switch to matches', 'puzzles', or 'squares'. What would you like to do?",
            "GOODBYE_MSG": "Goodbye!",
            "GOODBYE_MATCHES": "Thanks for playing matches! Your position is saved. See you next time!",
            "GOODBYE_PUZZLES": "Great job on the puzzles today! See you later!",
            "GOODBYE_SQUARES": "Excellent visualization practice! See you soon!",
            "REFLECT_MOVE": "You moved your {piece} to {square}. Let me think.",
            "AI_MOVE_RESPONSE": "I play {move}. Your turn.",
            "INVALID_MOVE_RESPONSE": "{move} is not a valid move. {error}",
            "FALLBACK_MSG": "Sorry, I don't know about that. Please try again.",
            "ERROR_MSG": "Sorry, I had trouble doing what you asked. Please try again.",
            "SQUARES_MODE_START": "Starting Squares mode. I will name a square, and you tell me if it's white or black. Ready? What color is {square}?",
            "PUZZLES_MODE_START": "Starting Puzzles mode. Here is a challenge. {description}. What is your move?",
            "CORRECT_ANSWER": "Correct!",
            "WRONG_ANSWER": "That's not right. Try again or ask for the next one.",
            "MODE_SWITCHED": "Switched to {mode} mode.",
            "NEXT_SQUARE": "Correct! Next one: what color is {square}?",
            "NEXT_PUZZLE": "Here is the next challenge. {description}. What is your move?",
            "PUZZLE_RETRY": "Give it another try. {description}",
            "READY_FOR_NEXT": "Ready for the next puzzle?",
            "BOARD_DESCRIPTION": "The board status is: White pieces: {white_pieces}. Black pieces: {black_pieces}.",
            "PIECE_POSITION": "{piece} at {square}",
            "PIECES": {
                "K": "King",
                "Q": "Queen",
                "R": "Rook",
                "B": "Bishop",
                "N": "Knight",
                "P": "Pawn"
            },
            "MENU_TITLE": "Blindfold Chess - Main Menu",
            "MENU_MATCHES": "Play a Match",
            "MENU_MATCHES_SUB": "Play against AI",
            "MENU_PUZZLES": "Puzzles",
            "MENU_PUZZLES_SUB": "Solve challenges",
            "MENU_SQUARES": "Squares",
            "MENU_SQUARES_SUB": "Visualize board"
        }
    },
    "es": {
        "translation": {
            "WELCOME_MSG": "¡Bienvenido a Ajedrez a Ciegas! ¿Te gustaría jugar una Partida, practicar con Puzzles o entrenar tu visualización con el modo Casillas?",
            "HELP_MSG": "Puedes jugar partidas, resolver puzzles o practicar los colores de las casillas. Di 'cambia a partidas', 'puzzles' o 'casillas'. ¿Qué te gustaría hacer?",
            "GOODBYE_MSG": "¡Adiós!",
            "GOODBYE_MATCHES": "¡Gracias por jugar! Tu partida ha sido guardada. ¡Hasta la próxima!",
            "GOODBYE_PUZZLES": "¡Buen trabajo con los puzzles hoy! ¡Hasta luego!",
            "GOODBYE_SQUARES": "¡Excelente práctica de visualización! ¡Nos vemos pronto!",
            "REFLECT_MOVE": "Has movido tu {piece} a {square}. Déjame pensar.",
            "AI_MOVE_RESPONSE": "Juego {move}. Tu turno.",
            "INVALID_MOVE_RESPONSE": "{move} no es un movimiento válido. {error}",
            "FALLBACK_MSG": "Lo siento, no sé nada sobre eso. Por favor, inténtalo de nuevo.",
            "ERROR_MSG": "Lo siento, tuve problemas para hacer lo que pediste. Por favor, inténtalo de nuevo.",
            "SQUARES_MODE_START": "Empezando el modo Casillas. Te diré una casilla y tú me dirás si es blanca o negra. ¿De qué color es {square}?",
            "PUZZLES_MODE_START": "Empezando el modo Puzzles. Aquí tienes un reto. {description}. ¿Cuál es tu movimiento?",
            "CORRECT_ANSWER": "¡Correcto!",
            "WRONG_ANSWER": "Eso no es correcto. Inténtalo de nuevo o pide el siguiente.",
            "MODE_SWITCHED": "Cambiado al modo {mode}.",
            "NEXT_SQUARE": "¡Correcto! Siguiente: ¿de qué color es {square}?",
            "NEXT_PUZZLE": "Aquí tienes el siguiente reto. {description}. ¿Cuál es tu movimiento?",
            "PUZZLE_RETRY": "Inténtalo de nuevo. {description}",
            "READY_FOR_NEXT": "¿Preparado para el siguiente puzzle?",
            "BOARD_DESCRIPTION": "El estado del tablero es: Piezas blancas: {white_pieces}. Piezas negras: {black_pieces}.",
            "PIECE_POSITION": "{piece} en {square}",
            "PIECES": {
                "K": "Rey",
                "Q": "Reina",
                "R": "Torre",
                "B": "Alfil",
                "N": "Caballo",
                "P": "Peón"
            },
            "MENU_TITLE": "Ajedrez a Ciegas - Menú Principal",
            "MENU_MATCHES": "Partida",
            "MENU_MATCHES_SUB": "Juega contra la IA",
            "MENU_PUZZLES": "Puzzles",
            "MENU_PUZZLES_SUB": "Resuelve retos",
            "MENU_SQUARES": "Casillas",
            "MENU_SQUARES_SUB": "Visualiza el tablero"
        }
    }
}
